import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface ReportSummary {
  total_visits: number;
  unique_visitors: number;
  avg_duration: number;
  busiest_directorate: string;
  from: string;
  to: string;
}

interface VisitRow {
  check_in_at: string;
  check_out_at: string | null;
  duration_minutes: number | null;
  status: string;
  badge_code: string | null;
  purpose_raw: string | null;
  first_name: string;
  last_name: string;
  organisation: string | null;
  host_name: string | null;
  directorate_abbr: string | null;
}

export function generatePDF(summary: ReportSummary, visits: VisitRow[]) {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header background
  doc.setFillColor(26, 77, 46); // #1A4D2E
  doc.rect(0, 0, pageWidth, 28, 'F');

  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('OHCS SmartGate', 14, 12);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text('Visitor Management Report', 14, 18);

  // Date range
  const fromFormatted = new Date(summary.from).toLocaleDateString('en-GB');
  const toFormatted = new Date(summary.to).toLocaleDateString('en-GB');
  doc.text(`${fromFormatted} — ${toFormatted}`, 14, 24);

  // Generated timestamp
  doc.setFontSize(8);
  doc.text(
    `Generated: ${new Date().toLocaleDateString('en-GB')} ${new Date().toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit', hour12: true })}`,
    pageWidth - 14, 24, { align: 'right' }
  );

  // Ghana flag bar
  const barY = 28;
  const third = pageWidth / 3;
  doc.setFillColor(206, 17, 38); // Red
  doc.rect(0, barY, third, 1.5, 'F');
  doc.setFillColor(252, 209, 22); // Gold
  doc.rect(third, barY, third, 1.5, 'F');
  doc.setFillColor(0, 107, 63); // Green
  doc.rect(third * 2, barY, third, 1.5, 'F');

  // Summary stats
  const summaryY = 35;
  doc.setTextColor(28, 24, 16);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('Summary', 14, summaryY);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(107, 99, 82);

  const stats = [
    `Total Visits: ${summary.total_visits}`,
    `Unique Visitors: ${summary.unique_visitors}`,
    `Avg Duration: ${summary.avg_duration}m`,
    `Busiest Directorate: ${summary.busiest_directorate}`,
  ];
  stats.forEach((stat, i) => {
    doc.text(stat, 14 + (i * 65), summaryY + 6);
  });

  // Table
  const tableData = visits.map(v => [
    new Date(v.check_in_at).toLocaleDateString('en-GB'),
    `${v.first_name} ${v.last_name}`,
    v.organisation ?? '',
    v.host_name ?? '',
    v.directorate_abbr ?? '',
    (v.purpose_raw ?? '').substring(0, 30),
    new Date(v.check_in_at).toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit', hour12: true }),
    v.check_out_at ? new Date(v.check_out_at).toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit', hour12: true }) : '—',
    v.duration_minutes?.toString() ?? '—',
    v.status.replace('_', ' '),
  ]);

  autoTable(doc, {
    startY: summaryY + 12,
    head: [['Date', 'Visitor', 'Organisation', 'Host', 'Dir', 'Purpose', 'In', 'Out', 'Min', 'Status']],
    body: tableData,
    styles: {
      fontSize: 8,
      cellPadding: 2,
      lineColor: [232, 223, 201],
      lineWidth: 0.2,
    },
    headStyles: {
      fillColor: [26, 77, 46],
      textColor: 255,
      fontSize: 8,
      fontStyle: 'bold',
    },
    alternateRowStyles: {
      fillColor: [254, 252, 246],
    },
    margin: { left: 14, right: 14 },
  });

  // Footer on each page
  const pageCount = (doc as unknown as { getNumberOfPages: () => number }).getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(156, 146, 128);
    doc.text(
      'Generated by OHCS SmartGate \u2014 Visitor Management System',
      14,
      doc.internal.pageSize.getHeight() - 8
    );
    doc.text(
      `Page ${i} of ${pageCount}`,
      pageWidth - 14,
      doc.internal.pageSize.getHeight() - 8,
      { align: 'right' }
    );
  }

  return doc;
}
